---
- hosts: 172.31.35.213
  become: yes
  tasks:
  - name: execute linux directly
    command: hostname -f 
    register: myresult

  - name: view the first task result 
    debug:
     msg: "{{myresult}}"  
    
     