---
- hosts: 172.31.35.213
  become: yes
  tasks:
   - include_tasks: myfile.yml
   - name: create myfolder
     file:
      path: /home/ubuntu/myfolder
      state: directory
   - name: copy the file
     copy:
      src: mycopyfile
      dest: /home/ubuntu/mycopyfile.txt 
   - name: dynamic file
     template:
      src: mydynamicfile.j2
      dest: /var/www/html/index.html

   