--- 
- hosts: mywebservers
  become: yes
  tasks:
  - name: install webserver on ubuntu
    apt:
     name: "{{mywebserveronubuntu}}"
     state: present
    when: ansible_os_family== "Debian" 
  - name: start webserver on ubuntu
    service:
     name: "{{mywebserveronubuntu}}"
     state: started 
    when: ansible_os_family== "Debian"   
  - name: install webserver on Redhat 
    yum:
     name: "{{mywebserveronRedhat}}"
     state: present
    when: ansible_os_family== "RedHat" 
  - name: start webserver on Redhat
    service:
     name: "{{mywebserveronRedhat}}"
     state: started 
    when: ansible_os_family== "RedHat"     